kubeProxyReplacement: true
k8sServiceHost: 10.20.56.30
k8sServicePort: 6443

# L2 Announcement (ARP) ve CRD'ler
l2announcements:
  enabled: true
  # Büyük/küçük clusterlarda lease ayarlarını değiştirmek gerekebilir:
  # leaseDuration: 300s
  # leaseRenewDeadline: 200s
  # leaseRetryPeriod: 50s

# Pod IPAM (istenirse özelleştirilebilir)
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.42.0.0/16"
    clusterPoolIPv4MaskSize: 24

hubble:
  enabled: true

  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true
    service:
      enabled: true

  relay:
    enabled: true
    metrics:
      enabled: true
      port: 9965
      protocol: TCP
      targetPort: 9965
      serviceMonitor:
        enabled: true
      service:
        enabled: true

  ui:
    enabled: true
    service:
      type: NodePort
      nodePort: 31647

operator:
  enabled: true
  replicas: 1

agent: true

prometheus:
  enabled: true
  port: 9962
  serviceMonitor:
    enabled: true
  service:
    enabled: true
tls:
  enabled: false
