apiVersion: v1
kind: Service
metadata:
  name: cilium-agent-metrics
  namespace: kube-system
  labels:
    k8s-app: cilium
    app.kubernetes.io/name: cilium-agent
    app.kubernetes.io/part-of: cilium
spec:
  type: NodePort
  selector:
    k8s-app: cilium
  ports:
    - name: metrics
      port: 9962
      targetPort: prometheus
      protocol: TCP
      nodePort: 30861
