apiVersion: v1
kind: Service
metadata:
  name: hubble-metrics
  namespace: kube-system
  labels:
    k8s-app: hubble
spec:
  type: NodePort
  selector:
    k8s-app: cilium
  ports:
    - name: hubble-metrics
      port: 9965
      targetPort: 9965
      protocol: TCP
      nodePort: 30965
